[package]
name = "domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nutype.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
indexmap.workspace = true
rust_decimal.workspace = true
regex.workspace = true
email_address = { workspace = true }
url = { workspace = true }

[dev-dependencies]
serde_json.workspace = true
